title: Anthony Bruno
description: Anthony Bruno: Programmer, Soccer Fanatic, Australian
url: http://anthonybruno.me
author: AnthonyBrunoAUS
gems:
  - jekyll-seo-tag
highlighter: rouge
google_analytics: UA-81683429-1
