title: Anthony Bruno
description: Personal website of Anthony Bruno, an Australian computer science student with a passion for programming.
url: http://anthonybruno.me
author: AnthonyBrunoAUS
gems:
  - jekyll-seo-tag
