title: Anthony Bruno
description: "Anthony Bruno: Programmer, Soccer Fanatic, Australian"
url: http://anthonybruno.com.au
author: AnthonyBrunoAUS
gems:
  - jekyll-seo-tag
highlighter: rouge
collections:
  - links
