title: Anthony Bruno
description: "Anthony Bruno - Software Engineer"
url: https://anthonybruno.dev
highlighter: rouge
author: AnthonyBrunoAUS
twitter:
  username: AnthonyBrunoAUS
  card: summary
social:
  name: Anthony Bruno
  links:
    - https://twitter.com/AnthonyBrunoAUS
    - https://github.com/AussieGuy0
    - https://dev.to/aussieguy
    - https://au.linkedin.com/in/anthonybruno1996
plugins:
  - jekyll-seo-tag
  - jekyll-feed
