title: Anthony Bruno
description: "Anthony Bruno - Software Engineer"
url: https://anthonybruno.dev
highlighter: rouge
author: DownUnder_Dev
repository: AussieGuy0/AussieGuy0.github.io
twitter:
  username: DownUnder_Dev
  card: summary
social:
  name: Anthony Bruno
  links:
    - https://twitter.com/DownUnder_Dev
    - https://github.com/AussieGuy0
    - https://dev.to/aussieguy
    - https://au.linkedin.com/in/anthonybruno1996
plugins:
  - jekyll-seo-tag
  - jekyll-feed
exclude:
  - vendor
  - Makefile
collections:
  read_books:
    output: true
  tils:
    output: true
