name: Goodreads Sync

on: [push]

jobs:
  goodreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Specify the version of Go you are using

      - name: Run Go program
        working-directory: _scripts/goodreads
        run: go run *.go

      - uses: stefanzweifel/git-auto-commit-action@v5
